### ISSUE TITLE
[마이페이지] 스크린샷 이미지는 업로드가 안됨

### ISSUE THREAD

**Issue by Choi-JJunho** [BCSDLab/BCSD_INTERNAL_WEB#57]
![image](https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/49794401/4266f8c0-4b33-49fc-a63f-b5bd830af052)

**Comment by MinGu-Jeong** [comment]
파일명에 공백이 포함되면 업로드가 안되던문제로 API를 수정하여 해결했습니다.
https://github.com/BCSDLab/BCSD_INTERNAL_API/pull/4
